export function buildOnboardingText({ commandLabel, cfg }) {
  const blocks = [
    "Echo Memory plugin onboarding",
    "",
    "Quick connect in the local UI:",
    "1. Open the plugin local UI and go to the Setup sidebar.",
    "2. Choose Regular or End-to-end encryption before entering your email.",
    "3. Enter the 6-digit OTP from your inbox.",
    "4. If you chose End-to-end encryption, set a local PIN. The plugin saves only the cloud encryption config; the derived key stays in the browser session.",
    "5. The plugin verifies or creates your EchoMemory account, records your encryption preference, creates a scoped `ec_...` API key, and writes it to `~/.openclaw/.env`.",
    "6. The local UI refreshes into connected mode. You do not need to open the website or create an API key manually.",
    "",
    "Manual fallback:",
    "1. If you prefer, expand `Advanced: enter API key manually` in the Setup sidebar.",
    "2. Use an existing `ec_...` key there and save local settings.",
    "3. For website-based key management, open `https://www.iditor.com/api` after logging in.",
    "",
    "Install and config:",
    `- Fixed backend endpoint: \`${cfg.baseUrl}\`.`,
    `- Fixed web app endpoint for graph links: \`${cfg.webBaseUrl}\`.`,
    "- Required config: `apiKey`.",
    "- Optional config: `memoryDir`, `autoSync`, `syncIntervalMinutes`, `batchSize`, `requestTimeoutMs`.",
    "- In `openclaw.json`, set `tools.profile` to `full`. The default `coding` profile is too restrictive for normal plugin use.",
    "- If you want EchoMemory to fully own recall, also disable OpenClaw's core memory tools in `~/.openclaw/openclaw.json` with `tools.deny: [\"memory_search\", \"memory_get\"]`.",
    "- The local UI checkbox `Echo-only memory retrieval` only blocks those OpenClaw tools at runtime after Echo cloud access is verified. Adding `tools.deny` in `openclaw.json` is the stronger and recommended setup.",
    "- `memoryDir` resolution order: plugin config, `ECHOMEM_MEMORY_DIR`, then `~/.openclaw/workspace/memory`.",
    "- Current `.env` location: `~/.openclaw/.env`.",
    "- Legacy `.moltbot` and `.clawdbot` `.env` files are only read as a one-release migration bridge, and new saves should move to `~/.openclaw/.env`.",
    "- Restart `openclaw gateway` after install or config changes.",
    "",
    "Commands and usage:",
    `- \`${commandLabel} onboard\` returns this full setup guide.`,
    `- \`${commandLabel} view\` opens the local localhost workspace UI that reads your markdown files directly.`,
    `- \`${commandLabel} whoami\` verifies the current API key and scopes.`,
    `- \`${commandLabel} status\` checks local sync state and remote import status.`,
    `- \`${commandLabel} sync\` pushes markdown memories into EchoMem Cloud.`,
    `- \`${commandLabel} search <query>\` runs semantic memory retrieval.`,
    `- \`${commandLabel} graph\` opens the private cloud memory graph login page and \`${commandLabel} graph public\` opens the public memories page.`,
    `- \`${commandLabel} help\` returns the short command list.`,
    "",
    "Graph links and security:",
    `- Private graph access intentionally goes to \`${cfg.webBaseUrl}/login?next=/memory-graph\` so the user logs in again.`,
    "- The plugin no longer returns an auto-login bridge link for the personal graph.",
    `- Public graph access still goes to \`${cfg.webBaseUrl}/memories\`.`,
    "- This separation is intentional because the personal graph now includes entry points such as the developer API key dashboard.",
    "",
    "How retrieval works:",
    "- Manual retrieval: use the search command when you want deterministic memory lookup.",
    "- Natural retrieval: the plugin registers tools so OpenClaw can search EchoMem during normal chat when memory context is relevant.",
    "- Semantic search works better with topics or meaning than with overly literal phrase matching.",
    "- Good smoke test order: whoami, status, sync, then search for a known memory topic.",
    "",
    "Troubleshooting:",
    "- `This command requires authorization`: fix Slack/OpenClaw allowlists, then restart the gateway.",
    "- If the plugin seems blocked by permission or privacy restrictions, set `tools.profile` to `full` in `~/.openclaw/openclaw.json` and restart the gateway.",
    "- If the model still chooses OpenClaw `memory_search` instead of EchoMemory, add `tools.deny: [\"memory_search\", \"memory_get\"]` to `~/.openclaw/openclaw.json`, then restart `openclaw gateway`.",
    "- `plugin not found`: reinstall or relink the plugin, then restart the gateway.",
    "- Zero search results: confirm sync/import happened and the API key has `memory:read`.",
    "- Repo edits not taking effect: linked installs are safer than copied installs during active development.",
    "- If graph access fails, remember the private graph now requires a fresh browser login rather than a handoff link.",
  ];

  return {
    text: blocks.join("\n"),
  };
}
